### ISSUE TITLE
Couldn't read dependencies

### ISSUE THREAD

**Issue by raulra08** [MomchilGorchev/meteor-service-health#1]
Hi.
I have cloned the repo, installed meteor, upgrade nam to latest and then it failed to execute
`$ meteor npm install`
Error:
`npm ERR! install Couldn't read dependencies` 

```
$ npm --version
3.8.6
```

```
$ meteor --version
Meteor 1.2.1
```

```
$ npm install
/Users/.../meteor-service-health
└── busboy@0.2.12 
npm WARN enoent ENOENT: no such file or directory, open '/Users/.../meteor-service-health/package.json'
npm WARN meteor-service-health No description
npm WARN meteor-service-health No repository field.
npm WARN meteor-service-health No README data
npm WARN meteor-service-health No license field.
```

Think it could be related to the fact the package.json is empty?
Should I add the packages mentioned in the README?

**Comment by MomchilGorchev** [comment]
Hey @raulra08 , its been a while i haven't touch this project. No need to install the packages manually. Also, is the `nam` means to say `npm`? 
I'll try to reproduce fresh clone and build/run and will get back to you :)
Thanks and good luck

**Comment by raulra08** [comment]
Yes, nam it's actually npm, when copy pasting the dictionary renamed the word :)
Thanks let me know how it goes

**Comment by MomchilGorchev** [comment]
Hey @raulra08 i just cloned the repo and run it with no problems. It takes some time on the first run because it initaly fetches all packages.
Try again this time run it this way:
1. Clone the repo, e.g `git clone git@github.com:MomchilGorchev/meteor-service-health.git`
2. Navigate inside the folder and run `meteor`
Let me know if the issue still persist :)

**Comment by raulra08** [comment]
@MomchilGorchev it worked thank you.

I just simply had to call meteor instead of npm install ;)
